Docblock
EasyPost/easypost-python pull request #164
Opened 2022-03-17 23:31 UTC by jchen293

work in progress...

2022-03-18 18:09 UTC, nwithan8 commented on easypost/address.py
> +    mode : str
¿Por qué no los dos?

2022-03-18 19:24 UTC, jchen293 commented on easypost/address.py
> +    mode : str
It's more related to the type hint if I translated your question correctly.

2022-03-18 20:00 UTC, jchen293 commented on easypost/address.py
> +        """
For simplicity, we have decided to make the docstrings as a single summary line since we are working on the type hint in the other PR.

2022-03-18 20:11 UTC, Justintime50 requested changes

2022-03-18 20:11 UTC, Justintime50 commented on easypost/batch.py
> +        """Create and buy Batch."""
```suggestion
        """Create and buy a Batch."""
```

2022-03-18 20:11 UTC, Justintime50 commented on easypost/batch.py
> +        """Create a batch scanform."""
```suggestion
        """Create a scanform for a batch."""
```

2022-03-18 20:11 UTC, Justintime50 commented on easypost/easypost_object.py
> +    """Convert to EasyPost object."""
```suggestion
    """Convert a response to an EasyPost object."""
```

2022-03-18 20:11 UTC, Justintime50 commented on easypost/easypost_object.py
> +        """Update the current object with given value."""
```suggestion
        """Update the local object with changes from the API."""
```

2022-03-18 20:11 UTC, Justintime50 commented on easypost/requestor.py
> +        """Convert object to dict."""
```suggestion
        """If providing an object as a parameter to another object, only pass along the ID so the API will use the object reference correctly."""
```

2022-03-18 20:11 UTC, Justintime50 commented on easypost/requestor.py
> +        """Make a request by using the `urlfetch` library from Google app engine."""
Keep it generic when possible. Maybe we add or subtract from this.

```suggestion
        """Make a request by using the `urlfetch` library."""
```

2022-03-18 20:11 UTC, Justintime50 commented on easypost/requestor.py
> +        """Encode params to a url."""
```suggestion
        """Encode params for a URL."""
```

2022-03-18 20:11 UTC, Justintime50 commented on easypost/requestor.py
> +        """Add params to the url."""
```suggestion
        """Add params to the URL."""
```

2022-03-18 20:11 UTC, Justintime50 commented on easypost/resource.py
> +        """Retrieve an object depends on the input params."""
```suggestion
        """Retrieve an object from the EasyPost API."""
```

2022-03-18 20:11 UTC, Justintime50 commented on easypost/resource.py
> +        """Refresh the current object with latest data from API response."""
```suggestion
        """Refresh the local object from the API response."""
```

2022-03-18 20:11 UTC, Justintime50 commented on easypost/resource.py
> +        """Convert the class to url."""
```suggestion
        """Generate a URL based on class name."""
```

2022-03-18 20:11 UTC, Justintime50 commented on easypost/resource.py
> +        """Convert instance to url with ID of the instance."""
```suggestion
        """Generate an instance URL based on the ID of the object."""
```

2022-03-18 20:11 UTC, Justintime50 commented on easypost/resource.py
> +        """Retrieve all for a specific class depends on the params input."""
```suggestion
        """Retrieve a list of records from the API."""
```

2022-03-18 20:11 UTC, Justintime50 commented on easypost/resource.py
> +        """Create a object depends on the params input."""
```suggestion
        """Create an EasyPost object."""
```

2022-03-18 20:11 UTC, Justintime50 commented on easypost/resource.py
> +        """Update current object."""
```suggestion
        """Update an EasyPost object."""
```

2022-03-18 20:11 UTC, Justintime50 commented on easypost/resource.py
> +        """Delete a specific item depends on the params."""
```suggestion
        """Delete an EasyPost object."""
```

2022-03-18 20:11 UTC, Justintime50 commented on easypost/shipment.py
> +        """Re-rate a shipment."""
```suggestion
        """Regenerate rates for a shipment."""
```

2022-03-18 20:11 UTC, Justintime50 commented on easypost/shipment.py
> +        """Convert the label format of the shipment."""
```suggestion
        """Convert the label format of a shipment."""
```

2022-03-18 20:11 UTC, Justintime50 commented on easypost/shipment.py
> +        """Get the lowest rate for a shipment."""
```suggestion
        """Get the lowest rate of a shipment."""
```

2022-03-18 20:11 UTC, Justintime50 commented on easypost/user.py
> +        """Create an user."""
```suggestion
        """Create a user."""
```

2022-03-18 20:11 UTC, Justintime50 commented on easypost/user.py
> +        """Retrieve an user."""
```suggestion
        """Retrieve a user."""
```

2022-03-18 20:11 UTC, Justintime50 commented on easypost/user.py
> +        """Retrieve me (the authenticated user)."""
```suggestion
        """Retrieve the authenticated user."""
```

2022-03-18 20:11 UTC, Justintime50 commented on easypost/user.py
> +        """Get my API key."""
```suggestion
        """Get the authenticated user's API keys."""
```

2022-03-18 20:11 UTC, Justintime50 commented on easypost/user.py
> +        """Update the User's Brand object."""
```suggestion
        """Update the User's Brand."""
```

2022-03-18 21:02 UTC, Justintime50 commented on easypost/address.py
> +    mode : str
It's redundant to have a docstring with all the properties of a class just to be repeated by the actual properties and their types again in code.

2022-03-21 18:59 UTC, nwithan8 submitted a review, later dismissed

2022-03-21 19:39 UTC, Justintime50 commented
Please rebase this PR, then I'll stamp.

2022-03-21 20:34 UTC, Justintime50 approved these changes

2022-03-21 20:37 UTC, nwithan8 approved these changes

2022-03-21 20:37 UTC, merged