remove message conditional check in address create and verify.
EasyPost/easypost-python pull request #175
Opened 2022-04-07 18:49 UTC by jchen293

Removes dead message conditional check in Address create and verify
Corrects assertion data and update fixture data due to AVCASS adjustments.

2022-04-07 18:51 UTC, Justintime50 requested changes
Please also remove the `carrier` logic from this function (I apologize, it's probably not in the original ticket) but is needed at this time too.

2022-04-07 18:57 UTC, Justintime50 approved these changes

2022-04-07 18:58 UTC, Justintime50 reviewed
Can we also add what was done here to the CHANGELOG (removed carrier param, remove conditional message check)?

2022-04-07 20:17 UTC, Justintime50 approved these changes

2022-04-08 17:00 UTC, jontsai approved these changes

2022-04-08 17:33 UTC, merged