Remove Unused Dependency: typing-extesions
EasyPost/easypost-python pull request #294
Opened 2023-08-11 18:40 UTC by gdrosos

## Summary

This pull request removes the unused dependency `typing-extensions` from the `setup.py` configuration file. The removal of this dependency is a finding from ongoing research aimed at identifying and eliminating code bloat within software projects.

## Rationale

The `typing_extensions` library was originally introduced to the project  in 35842786, however it  appears to be unused within the source code.
Removing this unused dependency  reduces the overall footprint of the application, mitigating potential security risks, and simplifying the dependency management process.

## Changes

- Removed the typing-extensions dependency from `setup.py`.

## Impact

- **Reduced Package Size**: The removal of this unused dependency will lead to a decrease in the overall size of the installed packages.
- **Simplified Dependency Tree**: Fewer dependencies make the project easier to maintain and can speed up installation.

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

2023-08-11 18:44 UTC, jchen293 approved these changes

2023-08-11 18:56 UTC, dcaballeroc approved these changes

2023-08-11 19:01 UTC, nwithan8 requested changes
If the dependency is unused, that is a mistake as we want to implement typing in this library. Recommend to reject.

2023-08-11 19:13 UTC, gdrosos commented
> If the dependency is unused, that is a mistake as we want to implement typing in this library. Recommend to reject.

Thank you, @nwithan8 , for your feedback.

Upon analyzing the current codebase, I've noticed that while the `typing` module from the python standard library is used, there aren't any references to the `typing-extensions` library. It was based on this observation that I created the PR.

2023-08-15 15:03 UTC, nwithan8 approved these changes

2023-08-15 15:03 UTC, merged