[bug] Cannot determine payment method when funding/deleting
EasyPost/easypost-python pull request #332
Opened 2024-04-08 19:37 UTC by nwithan8

# Description

- Use payment method object type as fallback when determining type for fund, delete functions

# Testing

- Update, add unit test to confirm legacy (by ID prefix) and new (by object type) both work to determine payment method type

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

2024-04-08 19:49 UTC, jchen293 approved these changes

2024-04-10 17:07 UTC, jchen293 approved these changes

2024-04-10 17:11 UTC, Justintime50 requested changes
Sigh. Github lost my comment, let me rewrite it

2024-04-10 17:43 UTC, nwithan8 commented on easypost/services/billing_service.py
> +            payment_method_object_type = payment_methods[payment_method_to_use].get("object", None)
I'm not confident that our API always returns an "object" key.

2024-04-10 17:45 UTC, Justintime50 commented on easypost/services/billing_service.py
> +            payment_method_object_type = payment_methods[payment_method_to_use].get("object", None)
Then all of the other language PRs we've put up will fail as written. Please ask the necessary teams internally to gain confidence in the changes you are making before we move forward.

2024-04-10 17:55 UTC, Justintime50 approved these changes

2024-04-10 17:55 UTC, Justintime50 commented on easypost/services/billing_service.py
> +            payment_method_object_type = payment_methods[payment_method_to_use].get("object", None)
I didn't realize that we are raising a `InvalidObjectError` below if we can't determine which endpoint to send it to - my bad. In this scenario, using `.get` here is fine for that reason.

2024-04-10 18:17 UTC, merged